version: '3.8'

services:
  core-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bankofcx
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=SuperSecretPassword123!
    # Intentionally vulnerable - no resource limits
    # Intentionally vulnerable - no healthcheck
    # Intentionally vulnerable - no restart policy
    depends_on:
      - db
      - kafka

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=bankofcx
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=SuperSecretPassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Intentionally vulnerable - no resource limits
    # Intentionally vulnerable - no healthcheck
    # Intentionally vulnerable - no restart policy

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    # Intentionally vulnerable - no resource limits
    # Intentionally vulnerable - no healthcheck
    # Intentionally vulnerable - no restart policy
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    # Intentionally vulnerable - no resource limits
    # Intentionally vulnerable - no healthcheck
    # Intentionally vulnerable - no restart policy

volumes:
  postgres_data:
    # Intentionally vulnerable - no volume backup
    # Intentionally vulnerable - no volume encryption 